/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * addcustomer.java
 *
 * Created on Apr 3, 2013, 3:07:02 PM
 */
package data_base_managment;

import com.sun.xml.internal.ws.developer.JAXBContextFactory;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.io.File;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.plaf.FileChooserUI;

/**
 *
 * @author user
 */
public class addcustomer extends javax.swing.JFrame {

    /**
     * Creates new form addcustomer
     */
    public addcustomer() {
        initComponents();
        setResizable(false);
        jButton5.setEnabled(false);


        nayo();

        t = new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                sdf = new SimpleDateFormat("YYYY/MM/dd HH:mm:a");
                Date d = new Date();
                String s = sdf.format(d);
                time.setText(s);
            }
        });
        t.start();



        Date d = new Date();
        SimpleDateFormat sd = new SimpleDateFormat("YYYY/MM/dd");
        String s = sd.format(d);
        date.setText(s);



    }

    public void nayo() {

        try {
            Statement s = data.getMain().createStatement();
            ResultSet rr = s.executeQuery("select  max(reference_id) from details");

            while (rr.next()) {

                int a = rr.getInt("max(reference_id)");
                a++;
                rn.setText(a + "");


            }



        } catch (Exception e) {
            e.printStackTrace();
        }


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        cn = new javax.swing.JTextField();
        rn = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        a1 = new javax.swing.JTextField();
        a2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        a3 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        dob = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        bp = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        pid = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        pep = new javax.swing.JTextField();
        photo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        date = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Footlight MT Light", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ADD CUSTOMER");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 20, 330, 60);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(40, 70, 1280, 20);

        jLabel3.setFont(new java.awt.Font("Footlight MT Light", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Contact Number");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(110, 650, 150, 20);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Saudi", "kuwait", "UAE", "Oman", "Baharen", "Jordhan", "Israel", "Qatar", "Lebanon", "Yemen", "Iran", "Cyprus", "Turkey", "Egypt", "Siriya" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(280, 90, 220, 30);

        jLabel4.setFont(new java.awt.Font("Footlight MT Light", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Select Country");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(110, 90, 140, 20);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "First Time", "Experienced", "7 Days" }));
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(280, 130, 220, 30);

        jLabel5.setFont(new java.awt.Font("Footlight MT Light", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Status");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(110, 130, 140, 20);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Direct", "Sub" }));
        jPanel1.add(jComboBox3);
        jComboBox3.setBounds(280, 170, 220, 30);

        jLabel6.setFont(new java.awt.Font("Footlight MT Light", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Bond");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(110, 170, 140, 20);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "House mate", "House Boy", "Driver", "Labours" }));
        jPanel1.add(jComboBox4);
        jComboBox4.setBounds(280, 210, 220, 30);

        jLabel7.setFont(new java.awt.Font("Footlight MT Light", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Job");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(110, 210, 140, 20);

        cn.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        cn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cnKeyTyped(evt);
            }
        });
        jPanel1.add(cn);
        cn.setBounds(280, 650, 220, 30);

        rn.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        rn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                rnKeyTyped(evt);
            }
        });
        jPanel1.add(rn);
        rn.setBounds(280, 250, 220, 30);

        jLabel8.setFont(new java.awt.Font("Footlight MT Light", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Reference No");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(110, 250, 140, 20);

        jLabel9.setFont(new java.awt.Font("Footlight MT Light", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Date");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(110, 330, 140, 20);

        name.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nameKeyTyped(evt);
            }
        });
        jPanel1.add(name);
        name.setBounds(280, 290, 220, 30);

        a1.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        a1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                a1KeyTyped(evt);
            }
        });
        jPanel1.add(a1);
        a1.setBounds(280, 370, 220, 30);

        a2.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        a2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                a2KeyTyped(evt);
            }
        });
        jPanel1.add(a2);
        a2.setBounds(280, 410, 220, 30);

        jLabel10.setFont(new java.awt.Font("Footlight MT Light", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Address");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(110, 370, 140, 20);

        a3.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        a3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                a3KeyTyped(evt);
            }
        });
        jPanel1.add(a3);
        a3.setBounds(280, 450, 220, 30);

        jLabel11.setFont(new java.awt.Font("Footlight MT Light", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Date Of Birth");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(110, 490, 140, 20);

        dob.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        dob.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                dobKeyTyped(evt);
            }
        });
        jPanel1.add(dob);
        dob.setBounds(280, 490, 220, 30);

        jLabel12.setFont(new java.awt.Font("Footlight MT Light", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Birth Place");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(330, 540, 140, 20);

        bp.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        bp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                bpKeyTyped(evt);
            }
        });
        jPanel1.add(bp);
        bp.setBounds(280, 530, 220, 30);

        jLabel13.setFont(new java.awt.Font("Footlight MT Light", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Passport ID");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(110, 570, 140, 20);

        pid.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        pid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pidKeyTyped(evt);
            }
        });
        jPanel1.add(pid);
        pid.setBounds(280, 570, 220, 30);

        jLabel14.setFont(new java.awt.Font("Footlight MT Light", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Passport EXP");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(110, 610, 140, 20);

        pep.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        pep.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pepKeyTyped(evt);
            }
        });
        jPanel1.add(pep);
        pep.setBounds(280, 610, 220, 30);

        photo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grp/photo.jpg"))); // NOI18N
        jPanel1.add(photo);
        photo.setBounds(1100, 80, 220, 200);

        jButton1.setFont(new java.awt.Font("Footlight MT Light", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grp/brows.jpg"))); // NOI18N
        jButton1.setText("Brows");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(1180, 310, 100, 40);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(620, 110, 20, 530);

        jButton2.setFont(new java.awt.Font("Footlight MT Light", 1, 16)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 0, 0));
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Documents\\NetBeansProjects\\data_base_managment\\src\\grp\\cancel.jpg")); // NOI18N
        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(1180, 580, 120, 40);

        jButton4.setFont(new java.awt.Font("Footlight MT Light", 1, 16)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 153, 0));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grp/Save.jpg"))); // NOI18N
        jButton4.setText("Save");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jButton4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jButton4KeyTyped(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(1050, 580, 120, 40);

        jRadioButton1.setBackground(null);
        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Footlight MT Light", 0, 18)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("Traning");
        jRadioButton1.setContentAreaFilled(false);
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton1);
        jRadioButton1.setBounds(640, 140, 170, 30);

        jRadioButton2.setBackground(null);
        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Footlight MT Light", 0, 18)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("Medical");
        jRadioButton2.setContentAreaFilled(false);
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton2);
        jRadioButton2.setBounds(640, 190, 170, 30);

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Footlight MT Light", 0, 18)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton3.setText("Medical Recheck");
        jRadioButton3.setContentAreaFilled(false);
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton3);
        jRadioButton3.setBounds(640, 240, 170, 30);

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Footlight MT Light", 0, 18)); // NOI18N
        jRadioButton4.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton4.setText("Depatuer");
        jRadioButton4.setContentAreaFilled(false);
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton4);
        jRadioButton4.setBounds(640, 290, 140, 25);
        jPanel1.add(date);
        date.setBounds(280, 330, 220, 30);

        jLabel15.setFont(new java.awt.Font("Footlight MT Light", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Name");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(110, 290, 140, 20);

        time.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        time.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(time);
        time.setBounds(1110, 10, 220, 50);

        jButton5.setText("View");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(650, 340, 70, 30);

        jButton3.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Documents\\NetBeansProjects\\data_base_managment\\src\\grp\\details1.png")); // NOI18N
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(1080, 390, 100, 100);

        jLabel16.setFont(new java.awt.Font("Footlight MT Light", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Documents\\NetBeansProjects\\data_base_managment\\src\\grp\\details1.png")); // NOI18N
        jLabel16.setText("Customer Summary");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(1100, 410, 240, 70);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Documents\\NetBeansProjects\\data_base_managment\\src\\grp\\passenger background.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1360, 710);
        jPanel1.add(jProgressBar1);
        jProgressBar1.setBounds(490, 370, 146, 14);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1346, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    Timer t;
    SimpleDateFormat sdf;
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            if (jRadioButton1.isSelected()) {



                Statement s = data.getMain().createStatement();
                s.executeUpdate("insert into details value('" + jComboBox1.getSelectedItem().toString() + "','" + jComboBox2.getSelectedItem().toString() + "','" + jComboBox3.getSelectedItem().toString() + "','" + jComboBox4.getSelectedItem().toString() + "','" + rn.getText() + "','" + name.getText() + "','" + date.getText() + "','" + a1.getText() + "','" + a2.getText() + "','" + a3.getText() + "','" + dob.getText() + "','" + bp.getText() + "','" + pid.getText() + "','" + pep.getText() + "','" + cn.getText() + "','" + jRadioButton1.getText() + "')");
                s.executeUpdate("insert into images value('" + rn.getText() + "','" + javapath + "')");

                JOptionPane.showMessageDialog(null, "Successfully Saved");

                name.setText(null);
                a1.setText("");
                a2.setText("");
                a3.setText("");
                dob.setText("");
                bp.setText("");
                pid.setText("");
                pep.setText("");
                cn.setText("");


                nayo();

            } else if (jRadioButton2.isSelected()) {



                Statement s = data.getMain().createStatement();
                s.executeUpdate("insert into details value('" + jComboBox1.getSelectedItem().toString() + "','" + jComboBox2.getSelectedItem().toString() + "','" + jComboBox3.getSelectedItem().toString() + "','" + jComboBox4.getSelectedItem().toString() + "','" + rn.getText() + "','" + name.getText() + "','" + date.getText() + "','" + a1.getText() + "','" + a2.getText() + "','" + a3.getText() + "','" + dob.getText() + "','" + bp.getText() + "','" + pid.getText() + "','" + pep.getText() + "','" + cn.getText() + "','" + jRadioButton2.getText() + "')");
                s.executeUpdate("insert into images value('" + rn.getText() + "','" + javapath + "')");
                name.setText("");
                a1.setText("");
                a2.setText("");
                a3.setText("");
                dob.setText("");
                bp.setText("");
                pid.setText("");
                pep.setText("");
                cn.setText("");

                JOptionPane.showMessageDialog(null, "Successfully Saved");
                nayo();


            } else if (jRadioButton3.isSelected()) {



                Statement s = data.getMain().createStatement();
                s.executeUpdate("insert into details value('" + jComboBox1.getSelectedItem().toString() + "','" + jComboBox2.getSelectedItem().toString() + "','" + jComboBox3.getSelectedItem().toString() + "','" + jComboBox4.getSelectedItem().toString() + "','" + rn.getText() + "','" + name.getText() + "','" + date.getText() + "','" + a1.getText() + "','" + a2.getText() + "','" + a3.getText() + "','" + dob.getText() + "','" + bp.getText() + "','" + pid.getText() + "','" + pep.getText() + "','" + cn.getText() + "','" + jRadioButton3.getText() + "')");
                s.executeUpdate("insert into images value('" + rn.getText() + "','" + javapath + "')");
                name.setText("");
                a1.setText("");
                a2.setText("");
                a3.setText("");
                dob.setText("");
                bp.setText("");
                pid.setText("");
                pep.setText("");
                cn.setText("");
                JOptionPane.showMessageDialog(null, "Successfully Saved");
                nayo();

            } else if (jRadioButton4.isSelected()) {


                Statement s = data.getMain().createStatement();
                s.executeUpdate("insert into details value('" + jComboBox1.getSelectedItem().toString() + "','" + jComboBox2.getSelectedItem().toString() + "','" + jComboBox3.getSelectedItem().toString() + "','" + jComboBox4.getSelectedItem().toString() + "','" + rn.getText() + "','" + name.getText() + "','" + date.getText() + "','" + a1.getText() + "','" + a2.getText() + "','" + a3.getText() + "','" + dob.getText() + "','" + bp.getText() + "','" + pid.getText() + "','" + pep.getText() + "','" + cn.getText() + "','" + jRadioButton4.getText() + "')");
                s.executeUpdate("insert into images value('" + rn.getText() + "','" + javapath + "')");

                name.setText("");
                date.setText("");
                a1.setText("");
                a2.setText("");
                a3.setText("");
                dob.setText("");
                bp.setText("");
                pid.setText("");
                pep.setText("");
                cn.setText("");

                JOptionPane.showMessageDialog(null, "Successfully Saved");
                nayo();






            }


        } catch (Exception e) {
            e.printStackTrace();
        }
        nayo();







    }//GEN-LAST:event_jButton4ActionPerformed
    String javapath;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            JFileChooser f = new JFileChooser();
            f.showOpenDialog(this);

            File i = f.getSelectedFile();
            String winpath = i.getAbsolutePath();
            System.out.println(winpath);

            javapath = winpath.replace("\\", "/");
            System.out.println(javapath);

            File fr = new File(javapath);
            Image im = ImageIO.read(i);
            im = im.getScaledInstance(photo.getWidth(), photo.getHeight(), Image.SCALE_SMOOTH);

            photo.setIcon(new ImageIcon(im));

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed

        if (jRadioButton1.isSelected()) {

            jRadioButton2.setEnabled(false);
            jRadioButton3.setEnabled(false);
            jRadioButton4.setEnabled(false);

            jButton5.setEnabled(true);

        }




    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        if (jRadioButton2.isSelected()) {

            jRadioButton1.setEnabled(false);
            jRadioButton3.setEnabled(false);
            jRadioButton4.setEnabled(false);
            jButton5.setEnabled(true);


        }        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        this.dispose();
        try {
            main_page m1 = new main_page();
            m1.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(addcustomer.class.getName()).log(Level.SEVERE, null, ex);
        }



    }//GEN-LAST:event_jButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        if (jRadioButton3.isSelected()) {

            jRadioButton1.setEnabled(false);
            jRadioButton2.setEnabled(false);
            jRadioButton4.setEnabled(false);
            jButton5.setEnabled(true);


}           }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void rnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rnKeyTyped

        System.out.println(evt.getKeyChar());

        char c = evt.getKeyChar();
        if (!(c >= '0' && c <= '9')) {

            evt.consume();

            Toolkit.getDefaultToolkit().beep();

        }



    }//GEN-LAST:event_rnKeyTyped

    private void nameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameKeyTyped
        System.out.println(evt.getKeyChar());

        char c = evt.getKeyChar();
        if (c >= '0' && c <= '9') {

            evt.consume();

            Toolkit.getDefaultToolkit().beep();
        }




    }//GEN-LAST:event_nameKeyTyped

    private void a1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_a1KeyTyped
    }//GEN-LAST:event_a1KeyTyped

    private void a2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_a2KeyTyped
        System.out.println(evt.getKeyChar());

        char c = evt.getKeyChar();
        if ((c >= '0' && c <= '9')) {

            evt.consume();
            Toolkit.getDefaultToolkit().beep();



        }




    }//GEN-LAST:event_a2KeyTyped

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        if (jRadioButton4.isSelected()) {

            jRadioButton1.setEnabled(false);
            jRadioButton2.setEnabled(false);
            jRadioButton3.setEnabled(false);



        }         // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        jRadioButton1.setEnabled(true);
        jRadioButton2.setEnabled(true);
        jRadioButton3.setEnabled(true);
        jRadioButton4.setEnabled(true);

        jButton5.setEnabled(false);





    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton4KeyTyped
        System.out.println(evt.getKeyChar());

        char c = evt.getKeyChar();

        if (c == KeyEvent.VK_ENTER) {

            jButton4.setText("aasa");


        }







    }//GEN-LAST:event_jButton4KeyTyped

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        this.dispose();
        summery su = new summery();
        su.setVisible(true);
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void a3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_a3KeyTyped
        System.out.println(evt.getKeyChar());
        
        char c = evt.getKeyChar();
        
        if(!(c<='0' && c>='9')){
        
        
        evt.consume();
        
        Toolkit.getDefaultToolkit().beep();
        
        }
        
        
        
    }//GEN-LAST:event_a3KeyTyped

    private void dobKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dobKeyTyped
 System.out.println(evt.getKeyChar());
        
        char c = evt.getKeyChar();
        
        if(!(c<='0' && c>='9')){
        
        
        evt.consume();
        
        Toolkit.getDefaultToolkit().beep();
        
        }
                // TODO add your handling code here:
    }//GEN-LAST:event_dobKeyTyped

    private void bpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bpKeyTyped
 System.out.println(evt.getKeyChar());
        
        char c = evt.getKeyChar();
        
        if(!(c<='0' && c>='9')){
        
        
        evt.consume();
        
        Toolkit.getDefaultToolkit().beep();
        
        }
                // TODO add your handling code here:
    }//GEN-LAST:event_bpKeyTyped

    private void pidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pidKeyTyped
 System.out.println(evt.getKeyChar());
        
        char c = evt.getKeyChar();
        
        if(!(c<='0' && c>='9')){
        
        
        evt.consume();
        
        Toolkit.getDefaultToolkit().beep();
        
        }
                // TODO add your handling code here:
    }//GEN-LAST:event_pidKeyTyped

    private void pepKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pepKeyTyped
 System.out.println(evt.getKeyChar());
        
        char c = evt.getKeyChar();
        
        if(!(c<='0' && c>='9')){
        
        
        evt.consume();
        
        Toolkit.getDefaultToolkit().beep();
        
        }
                // TODO add your handling code here:
    }//GEN-LAST:event_pepKeyTyped

    private void cnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cnKeyTyped
 System.out.println(evt.getKeyChar());
        
        char c = evt.getKeyChar();
        
        if(!(c<='0' && c>='9')){
        
        
        evt.consume();
        
        Toolkit.getDefaultToolkit().beep();
        
        }
                // TODO add your handling code here:
    }//GEN-LAST:event_cnKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addcustomer().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField a1;
    private javax.swing.JTextField a2;
    private javax.swing.JTextField a3;
    private javax.swing.JTextField bp;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField cn;
    private javax.swing.JTextField date;
    private javax.swing.JTextField dob;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField name;
    private javax.swing.JTextField pep;
    private javax.swing.JLabel photo;
    private javax.swing.JTextField pid;
    private javax.swing.JTextField rn;
    private javax.swing.JLabel time;
    // End of variables declaration//GEN-END:variables
}
