/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * addContracter.java
 *
 * Created on Jan 24, 2013, 3:35:32 PM
 */
package data_base_managment;

import java.awt.Toolkit;
import java.io.File;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import java.awt.Image;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author Umesh
 */
public class addContracter extends javax.swing.JFrame {

    /** Creates new form addContracter */
    public addContracter() {
        initComponents();
//        referanceno();
        date();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1354, 713));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Footlight MT Light", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Add Contracter");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 30, 260, 30);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(290, 50, 1000, 20);

        jLabel5.setFont(new java.awt.Font("Footlight MT Light", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Name             :-");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(140, 160, 140, 17);

        jLabel6.setFont(new java.awt.Font("Footlight MT Light", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Address          :-");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(140, 210, 150, 17);

        jLabel7.setFont(new java.awt.Font("Footlight MT Light", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText(" Nic                :-");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(140, 330, 140, 17);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(370, 150, 190, 20);

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jTextField3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField3FocusLost(evt);
            }
        });
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField3KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField3KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField3);
        jTextField3.setBounds(370, 320, 190, 20);

        jLabel3.setFont(new java.awt.Font("Footlight MT Light", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Contact           :-");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(140, 370, 150, 17);

        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField4KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField4);
        jTextField4.setBounds(370, 360, 190, 20);

        jLabel4.setFont(new java.awt.Font("Footlight MT Light", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Introduce by    :-");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(140, 410, 150, 17);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(370, 410, 190, 20);

        jLabel8.setFont(new java.awt.Font("Footlight MT Light", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Refarance No :-");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(140, 110, 130, 17);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grp/photo.jpg"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(900, 70, 170, 210);

        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField2KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(370, 110, 190, 20);

        jLabel10.setFont(new java.awt.Font("Footlight MT Light", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Photo");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(780, 110, 70, 17);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tharindu\\Documents\\NetBeansProjects\\data_base_managment\\src\\grp\\1368510607_file-manager.png")); // NOI18N
        jButton1.setText("Brows");
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(930, 300, 150, 80);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(153, 0, 0));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grp/1368510506_gtk-cancel.png"))); // NOI18N
        jButton4.setText("Cancel");
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(1080, 550, 150, 60);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(153, 0, 0));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grp/1368510424_save.png"))); // NOI18N
        jButton2.setText("Save");
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(890, 540, 140, 80);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 0, 570);
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, 0, 0, 590);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(153, 0, 0));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grp/backward.png"))); // NOI18N
        jButton3.setText("Back");
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(680, 540, 160, 70);

        jLabel13.setFont(new java.awt.Font("Footlight MT Light", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText(" Date :-");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(140, 510, 80, 40);

        jLabel14.setFont(new java.awt.Font("Footlight MT Light", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("jLabel14");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(590, 380, 700, 110);

        jLabel15.setFont(new java.awt.Font("Footlight MT Light", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("V");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(570, 323, 40, 17);

        jLabel16.setFont(new java.awt.Font("Footlight MT Light", 0, 17)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("jLabel16");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(380, 520, 180, 20);
        getContentPane().add(jTextField6);
        jTextField6.setBounds(370, 210, 190, 80);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grp/passenger background.jpg"))); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(0, 0, 1350, 710);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
//        this.dispose();
//        main q = new main();
//        q.setVisible(true);
}//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            JFileChooser jf=new JFileChooser();
            jf.showOpenDialog(this);
            File f=jf.getSelectedFile();
            String winpath=f.getAbsolutePath();
            System.out.println(winpath);
            String javapath =winpath.replace("//", "/");
            
            File ff=new File(javapath);
            Image img=ImageIO.read(ff);
            img=img.getScaledInstance(jLabel9.getWidth(), jLabel9.getWidth(),Image.SCALE_SMOOTH);
            jLabel9.setIcon(new ImageIcon(img));
            
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyTyped
        char c=evt.getKeyChar();
        if (c>'0'& c>'9') {
            evt.consume();
            jLabel14.setText("Pleace type a number");
        }Toolkit.getDefaultToolkit().beep();
    }//GEN-LAST:event_jTextField3KeyTyped

    private void jTextField4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyTyped
        char c=evt.getKeyChar();
        if (c>'0'& c>'9') {
            evt.consume();
           jLabel14.setText("Pleace type a number");
        }Toolkit.getDefaultToolkit().beep();
    }//GEN-LAST:event_jTextField4KeyTyped

    private void jTextField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyTyped
        char c=evt.getKeyChar();
        if (c>'0'& c>'9') {
            evt.consume();
            jLabel14.setText("Pleace type a number");
        }Toolkit.getDefaultToolkit().beep();
    }//GEN-LAST:event_jTextField2KeyTyped

    private void jTextField3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField3FocusLost
        if (jTextField3.getText().length()>9) {
            jLabel14.setText("check NIC number it contain more than 9 numbers");
            
        }
        
    }//GEN-LAST:event_jTextField3FocusLost

    private void jTextField3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyPressed
        String s1=jTextField3.getText();
        String s2=s1.substring(0,2);
        String s6=19+""+s2;
        System.out.println(s6);
        Double d1=Double.parseDouble(s6);
        Date d=new Date();
        SimpleDateFormat sd=new SimpleDateFormat("yyyy");
        String s4=sd.format(d);
        System.out.println(s4);
       
        Double d2=Double.parseDouble(s4);
        Double d3=d2-d1;
        if (d3<18) {
            jLabel14.setText("applicant is not eligable to go abroad because she is"+d3.toString()+"years old");
            
        }
        
       
       
    }//GEN-LAST:event_jTextField3KeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            Statement s=contracter.getmainConnection().createStatement();
            String ss;
            ss = jTextField3.getText()+"V";
            s.executeUpdate("insert into contractor_details values('"+jTextField1.getText()+"' '"+jTextField6.getText()+"' '"+ss+"' '"+jTextField4.getText()+"' '"+jTextField5.getText()+"' '"+jLabel16.getText()+"')");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new addContracter().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables

    private void referanceno() {
        try {
            Statement s=contracter.getmainConnection().createStatement();
            ResultSet rs= s.executeQuery("select max(HP) from table");
  
            while (rs.next()) {
                int i=rs.getInt(null);
                i++;
                jTextField2.setText(i+"");
                
            }
        } catch (Exception e) {
        e.printStackTrace();
        }
    }

    public void date() {
      new Thread(new Runnable() {

            @Override
            public void run() {
                while (true) {
                     Date d=new Date();
        SimpleDateFormat sd=new SimpleDateFormat("yyyy-MM-dd:mm:ss");
        String s4=sd.format(d);
        jLabel16.setText(s4);
                    
                }
        
            }
        }).start();
    }
}
