/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * addpaymentreasons.java
 *
 * Created on Apr 26, 2013, 1:28:52 PM
 */
package data_base_managment;

import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author bandara
 */
public class addpaymentreasons extends javax.swing.JFrame {

    /** Creates new form addpaymentreasons */
    public addpaymentreasons() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        amount = new javax.swing.JTextField();
        jButton21 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        reason = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel13.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 204, 255));
        jLabel13.setText("Add Payment Reason");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(10, 10, 200, 22);

        jLabel17.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Amount");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(70, 110, 90, 30);
        jPanel1.add(amount);
        amount.setBounds(200, 120, 140, 30);

        jButton21.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jButton21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/Save.jpg"))); // NOI18N
        jButton21.setText("Add");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton21);
        jButton21.setBounds(50, 180, 110, 30);

        jButton18.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jButton18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/clear.jpg"))); // NOI18N
        jButton18.setText("Edit");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton18);
        jButton18.setBounds(210, 180, 110, 30);

        jButton15.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/finance.png"))); // NOI18N
        jButton15.setText("Back");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton15);
        jButton15.setBounds(300, 250, 180, 50);

        jButton16.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/cancel.jpg"))); // NOI18N
        jButton16.setText("Delete");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton16);
        jButton16.setBounds(350, 180, 140, 30);

        jLabel18.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Reason");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(70, 80, 90, 30);
        jPanel1.add(reason);
        reason.setBounds(200, 80, 140, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/ada.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 0, 320);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        try {
            Statement s = Agendata.getagenf().createStatement();
            s.executeUpdate("insert into paymentreason values('" + reason.getText() + "','" + amount.getText() + "')");
//             ResultSet rs=s.executeQuery("select * from paymentreason");
//             Vector v=new Vector();
//             while (rs.next()) {                
//                DefaultComboBoxModel dd=new DefaultComboBoxModel(v);
//                jcombobo
//            }
        } catch (Exception e) {
            e.printStackTrace();
        }


}//GEN-LAST:event_jButton21ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        try {
            Statement s = Agendata.getagenf().createStatement();
            s.executeUpdate("update paymentreason set reason='" + reason.getText() + "',amount='" + amount.getText() + "'");
        } catch (Exception e) {
            e.printStackTrace();
        }

}//GEN-LAST:event_jButton18ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        this.dispose();
        settings s = new settings();
        s.setVisible(true);
}//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        try {
               Statement s=Agendata.getagenf().createStatement();
        s.executeUpdate("delete * from paymentreason where reason='"+reason.getText()+"'");
        } catch (Exception e) {
        }
      
}//GEN-LAST:event_jButton16ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new addpaymentreasons().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amount;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton21;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField reason;
    // End of variables declaration//GEN-END:variables
}
