/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * convoucher.java
 *
 * Created on Apr 25, 2013, 12:02:21 PM
 */
package data_base_managment;

import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author bandara
 */
public class convoucher extends javax.swing.JFrame {

    /** Creates new form convoucher */
    public convoucher() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel37 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel36 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jTextField17 = new javax.swing.JTextField();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jTextField18 = new javax.swing.JTextField();
        time = new javax.swing.JTextField();
        jButton31 = new javax.swing.JButton();
        jRadioButton11 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jLabel26 = new javax.swing.JLabel();
        date = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox();
        jButton32 = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jRadioButton13 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel35 = new javax.swing.JLabel();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jSeparator8.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator8);
        jSeparator8.setBounds(1190, 80, 20, 580);

        jLabel37.setFont(new java.awt.Font("Bookman Old Style", 3, 18)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(240, 240, 240));
        jLabel37.setText("Enter the Contractor ID");
        jPanel1.add(jLabel37);
        jLabel37.setBounds(60, 160, 260, 30);
        jPanel1.add(jSeparator9);
        jSeparator9.setBounds(20, 80, 1330, 10);

        jLabel36.setFont(new java.awt.Font("MS Mincho", 3, 24)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(0, 255, 0));
        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grp/Green-Dollar-icon.png"))); // NOI18N
        jLabel36.setText("Contractor Finance Activities.");
        jPanel1.add(jLabel36);
        jLabel36.setBounds(20, 40, 460, 50);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grp/photo.jpg"))); // NOI18N
        jPanel1.add(jLabel19);
        jLabel19.setBounds(560, 100, 180, 190);
        jPanel1.add(jTextField12);
        jTextField12.setBounds(340, 160, 200, 30);

        jButton2.setFont(new java.awt.Font("Bookman Old Style", 3, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(204, 0, 0));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grp/finance.png"))); // NOI18N
        jButton2.setText("Back to main page");
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(1000, 0, 290, 80);

        jButton26.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jButton26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grp/Save.jpg"))); // NOI18N
        jButton26.setText("Save");
        jButton26.setBorderPainted(false);
        jButton26.setContentAreaFilled(false);
        jPanel1.add(jButton26);
        jButton26.setBounds(780, 600, 110, 33);

        jLabel24.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jLabel24.setText("Payment For");
        jPanel1.add(jLabel24);
        jLabel24.setBounds(120, 340, 130, 22);

        jButton27.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jButton27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grp/user-group-icon2.png"))); // NOI18N
        jButton27.setText("Switch to contractor details");
        jButton27.setBorderPainted(false);
        jButton27.setContentAreaFilled(false);
        jPanel1.add(jButton27);
        jButton27.setBounds(740, 230, 350, 50);

        jButton28.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jButton28.setText("Time");
        jButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton28ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton28);
        jButton28.setBounds(120, 580, 90, 31);
        jPanel1.add(jTextField17);
        jTextField17.setBounds(800, 340, 240, 20);

        jButton29.setFont(new java.awt.Font("Bookman Old Style", 2, 18)); // NOI18N
        jButton29.setForeground(new java.awt.Color(204, 0, 0));
        jButton29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grp/Green-Dollar-icon.png"))); // NOI18N
        jButton29.setText("Income");
        jButton29.setBorderPainted(false);
        jButton29.setContentAreaFilled(false);
        jPanel1.add(jButton29);
        jButton29.setBounds(1200, 360, 150, 40);

        jButton30.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jButton30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grp/details1.png"))); // NOI18N
        jButton30.setText("View");
        jButton30.setBorderPainted(false);
        jButton30.setContentAreaFilled(false);
        jPanel1.add(jButton30);
        jButton30.setBounds(600, 580, 150, 70);
        jPanel1.add(jTextField18);
        jTextField18.setBounds(270, 490, 230, 20);
        jPanel1.add(time);
        time.setBounds(270, 590, 230, 20);

        jButton31.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jButton31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grp/cancel.jpg"))); // NOI18N
        jButton31.setText("Delete");
        jButton31.setBorderPainted(false);
        jButton31.setContentAreaFilled(false);
        jPanel1.add(jButton31);
        jButton31.setBounds(840, 520, 140, 33);

        buttonGroup1.add(jRadioButton11);
        jRadioButton11.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jRadioButton11.setText("Both");
        jRadioButton11.setContentAreaFilled(false);
        jPanel1.add(jRadioButton11);
        jRadioButton11.setBounds(900, 450, 110, 25);

        buttonGroup1.add(jRadioButton10);
        jRadioButton10.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jRadioButton10.setText("Cash");
        jRadioButton10.setContentAreaFilled(false);
        jPanel1.add(jRadioButton10);
        jRadioButton10.setBounds(900, 390, 110, 25);

        jLabel26.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jLabel26.setText("Total Payment");
        jPanel1.add(jLabel26);
        jLabel26.setBounds(120, 490, 140, 22);
        jPanel1.add(date);
        date.setBounds(270, 540, 230, 20);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ticket", "Medical", " " }));
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(270, 340, 230, 20);

        jButton32.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jButton32.setText("Date");
        jButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton32ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton32);
        jButton32.setBounds(120, 530, 90, 30);

        jLabel28.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jLabel28.setText("Payment method");
        jPanel1.add(jLabel28);
        jLabel28.setBounds(660, 390, 160, 22);

        buttonGroup1.add(jRadioButton13);
        jRadioButton13.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jRadioButton13.setText("Cheque");
        jRadioButton13.setContentAreaFilled(false);
        jPanel1.add(jRadioButton13);
        jRadioButton13.setBounds(900, 420, 110, 25);

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(380, 370, 120, 110);

        jLabel35.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jLabel35.setText("Amount");
        jPanel1.add(jLabel35);
        jLabel35.setBounds(670, 340, 90, 22);

        jButton33.setFont(new java.awt.Font("Bookman Old Style", 2, 18)); // NOI18N
        jButton33.setForeground(new java.awt.Color(204, 0, 0));
        jButton33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grp/searchf.png"))); // NOI18N
        jButton33.setText("Search");
        jButton33.setBorderPainted(false);
        jButton33.setContentAreaFilled(false);
        jPanel1.add(jButton33);
        jButton33.setBounds(1170, 110, 180, 60);

        jButton34.setBackground(new java.awt.Color(0, 0, 0));
        jButton34.setFont(new java.awt.Font("Bookman Old Style", 2, 18)); // NOI18N
        jButton34.setForeground(new java.awt.Color(204, 0, 0));
        jButton34.setText("Settings");
        jButton34.setBorderPainted(false);
        jButton34.setContentAreaFilled(false);
        jButton34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton34ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton34);
        jButton34.setBounds(1200, 220, 150, 80);

        jButton37.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jButton37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grp/Windows-View-Detail-icon.png"))); // NOI18N
        jButton37.setText("Get Total");
        jButton37.setBorderPainted(false);
        jButton37.setContentAreaFilled(false);
        jPanel1.add(jButton37);
        jButton37.setBounds(520, 510, 180, 50);

        jButton38.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jButton38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grp/clear.jpg"))); // NOI18N
        jButton38.setText("Edit");
        jButton38.setBorderPainted(false);
        jButton38.setContentAreaFilled(false);
        jPanel1.add(jButton38);
        jButton38.setBounds(700, 520, 110, 30);

        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel2);
        jLabel2.setBounds(100, 300, 1060, 360);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grp/passenger background.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1360, 710);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1354, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 674, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
        mainslide mq=new mainslide();
        mq.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton34ActionPerformed
        this.dispose();
        settings se=new settings();
        se.setVisible(true);
    }//GEN-LAST:event_jButton34ActionPerformed

    private void jButton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton32ActionPerformed
        Date dg=new Date();
        SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
        String e=sdf.format(dg);
        date.setText(e);
    }//GEN-LAST:event_jButton32ActionPerformed

    private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton28ActionPerformed
       Date dr=new Date();
       SimpleDateFormat qw=new SimpleDateFormat("yyyy-MM-dd hh:mm:ss");
       String q=qw.format(dr);
       String arr[]=q.split(" ");
       time.setText(arr[1]);
       
    }//GEN-LAST:event_jButton28ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new convoucher().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField date;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton13;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField time;
    // End of variables declaration//GEN-END:variables
}
