/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * customer_details.java
 *
 * Created on Apr 3, 2013, 3:05:19 PM
 */
package data_base_managment;

import java.awt.Image;
import java.io.File;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author Dell
 */
public class customer_details extends javax.swing.JFrame {

    /** Creates new form customer_details */
    public customer_details() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        country = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        status = new javax.swing.JTextField();
        bond = new javax.swing.JTextField();
        job = new javax.swing.JTextField();
        referenceno = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        address1 = new javax.swing.JTextField();
        address2 = new javax.swing.JTextField();
        address3 = new javax.swing.JTextField();
        birthplace = new javax.swing.JTextField();
        passportid = new javax.swing.JTextField();
        passportexp = new javax.swing.JTextField();
        dateofbirth = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        contactnumber = new javax.swing.JTextField();
        id = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Footlight MT Light", 0, 18));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Status");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 70, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 1310, 10));

        jLabel2.setFont(new java.awt.Font("Footlight MT Light", 1, 36));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CUSTOMER DETAILS");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 590, 60));

        jLabel4.setFont(new java.awt.Font("Footlight MT Light", 0, 18));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Search By ID");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 120, 120, 30));

        jLabel8.setFont(new java.awt.Font("Footlight MT Light", 0, 18));
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Bond");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 70, -1));

        jLabel9.setFont(new java.awt.Font("Footlight MT Light", 0, 18));
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Date Of Birth");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 460, 110, -1));

        jLabel10.setFont(new java.awt.Font("Footlight MT Light", 0, 18));
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Job");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 70, 20));

        jLabel11.setFont(new java.awt.Font("Footlight MT Light", 0, 18));
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Contact Number");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 620, 130, -1));

        jLabel12.setFont(new java.awt.Font("Footlight MT Light", 0, 18));
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Reference no");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 130, -1));

        jLabel13.setFont(new java.awt.Font("Footlight MT Light", 0, 18));
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Passport ID");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 540, 120, -1));

        jLabel14.setFont(new java.awt.Font("Footlight MT Light", 0, 18));
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Birth place");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 500, 100, 20));

        jLabel15.setFont(new java.awt.Font("Footlight MT Light", 0, 18));
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Name");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 70, -1));

        jLabel16.setFont(new java.awt.Font("Footlight MT Light", 0, 18));
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Adress");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, 70, -1));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 110, 30, 530));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grp/photo.jpg"))); // NOI18N
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 100, 130, 160));

        jButton1.setFont(new java.awt.Font("Footlight MT Light", 0, 14));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grp/brows.jpg"))); // NOI18N
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 120, 110, 30));

        jButton2.setFont(new java.awt.Font("Footlight MT Light", 1, 14));
        jButton2.setForeground(new java.awt.Color(204, 0, 0));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grp/cancel.jpg"))); // NOI18N
        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 550, 110, 40));

        jButton3.setFont(new java.awt.Font("Footlight MT Light", 1, 14));
        jButton3.setForeground(new java.awt.Color(255, 0, 0));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grp/edit.jpg"))); // NOI18N
        jButton3.setText("Edit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 550, 120, 40));

        country.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countryActionPerformed(evt);
            }
        });
        jPanel1.add(country, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 210, -1));

        jButton4.setFont(new java.awt.Font("Footlight MT Light", 1, 14));
        jButton4.setForeground(new java.awt.Color(0, 102, 0));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grp/finance.jpg"))); // NOI18N
        jButton4.setText("Finance");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 550, 140, 40));
        jPanel1.add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 210, -1));
        jPanel1.add(bond, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 210, -1));
        jPanel1.add(job, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 210, -1));

        referenceno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                referencenoActionPerformed(evt);
            }
        });
        jPanel1.add(referenceno, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 210, -1));
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 210, -1));
        jPanel1.add(address1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 210, -1));
        jPanel1.add(address2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 390, 210, -1));
        jPanel1.add(address3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 420, 210, -1));
        jPanel1.add(birthplace, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 500, 210, -1));
        jPanel1.add(passportid, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 540, 210, -1));
        jPanel1.add(passportexp, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 580, 210, -1));
        jPanel1.add(dateofbirth, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 460, 210, -1));

        jLabel18.setFont(new java.awt.Font("Footlight MT Light", 0, 18));
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Passport EXP");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 580, 130, -1));

        contactnumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactnumberActionPerformed(evt);
            }
        });
        contactnumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                contactnumberKeyTyped(evt);
            }
        });
        jPanel1.add(contactnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 620, 210, -1));

        id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idKeyTyped(evt);
            }
        });
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 120, 60, 30));

        jLabel5.setFont(new java.awt.Font("Footlight MT Light", 0, 18));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Country");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 70, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grp/passenger background.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, 0, 1360, 710));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void countryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_countryActionPerformed

    private void contactnumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactnumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactnumberActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            Statement s=NewClass.getagencyConnection().createStatement();
           ResultSet rs= s.executeQuery("select * from customer_details where id like  '%"+id.getText()+"%' order by ");
           
           while(rs.next()){
                country.setText(rs.getString("country"));
                status.setText(rs.getString("status"));
                bond.setText(rs.getString("bond"));
                job.setText(rs.getString("job"));
                referenceno.setText(rs.getString("reference_no"));
                name.setText(rs.getString("name"));
                address1.setText(rs.getString("address1"));
                address2.setText(rs.getString("address2"));
                address3.setText(rs.getString("address3"));
                dateofbirth.setText(rs.getString("date_of_birth"));
                birthplace.setText(rs.getString("birth_place"));
                passportid.setText(rs.getString("passport_id"));
                passportexp.setText(rs.getString("passport_exp"));
                contactnumber.setText(rs.getString("contact_number"));
                 
                File f=new File(rs.getString(2));
                Image img= ImageIO.read(f);
                img=img.getScaledInstance(jLabel17.getWidth(), jLabel17.getHeight(),Image.SCALE_SMOOTH);
                jLabel17.setIcon(new ImageIcon(img));
                
              }
        
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            Statement s=NewClass.getagencyConnection().createStatement();
            s.executeUpdate("update customer_details set country='"+country.getText()+"',status='"+status.getText()+"',bond='"+bond.getText()+"',job='"+job.getText()+"',reference_no='"+referenceno.getText()+"',name='"+name.getText()+"',address1='"+address1.getText()+"',address2='"+address2.getText()+"',address3='"+address3.getText()+"',date_of_birth='"+dateofbirth.getText()+"',birth_place='"+birthplace.getText()+"',passport_id='"+passportid.getText()+"',passport_exp='"+passportexp.getText()+"',contact_number='"+contactnumber.getText()+"' where id ='"+id.getText()+"' ");
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void idKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idKeyTyped
     char c=evt.getKeyChar();
     if(!(c>='0' && c<='9')){
     evt.consume();
     }
     
    }//GEN-LAST:event_idKeyTyped

    private void contactnumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contactnumberKeyTyped
        char c=evt.getKeyChar();
     if(!(c>='0' && c<='9')){
     evt.consume();
     }
     
    }//GEN-LAST:event_contactnumberKeyTyped

    private void referencenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_referencenoActionPerformed
      
    }//GEN-LAST:event_referencenoActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
     
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new customer_details().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address1;
    private javax.swing.JTextField address2;
    private javax.swing.JTextField address3;
    private javax.swing.JTextField birthplace;
    private javax.swing.JTextField bond;
    private javax.swing.JTextField contactnumber;
    private javax.swing.JTextField country;
    private javax.swing.JTextField dateofbirth;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField job;
    private javax.swing.JTextField name;
    private javax.swing.JTextField passportexp;
    private javax.swing.JTextField passportid;
    private javax.swing.JTextField referenceno;
    private javax.swing.JTextField status;
    // End of variables declaration//GEN-END:variables
}
