/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package data_base_managment;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
//import javax.swing.UnsupportedLookAndFeelException;
//import javax.swing.plaf.synth.SynthLookAndFeel;

/**
 *
 * @author user
 */
public class main_page extends javax.swing.JFrame {

    /**
     * Creates new form main_page
     */
    public main_page() throws Exception {
        //UIManager.setLookAndFeel(new SynthLookAndFeel());
        
        initComponents();
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Documents\\user2.png")); // NOI18N
        jButton1.setRolloverSelectedIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Documents\\user2.png")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(220, 180, 64, 80);

        jLabel3.setFont(new java.awt.Font("Footlight MT Light", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Documents\\user2.png")); // NOI18N
        jLabel3.setText("Add Customer");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(220, 190, 310, 64);

        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setRolloverIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Documents\\details1.png")); // NOI18N
        jButton2.setRolloverSelectedIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Documents\\details1.png")); // NOI18N
        jPanel1.add(jButton2);
        jButton2.setBounds(220, 280, 64, 80);

        jLabel2.setFont(new java.awt.Font("Footlight MT Light", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Documents\\details1.png")); // NOI18N
        jLabel2.setText("Customer Details");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(220, 290, 350, 64);

        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setRolloverIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Documents\\contractor.png")); // NOI18N
        jButton3.setRolloverSelectedIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Documents\\contractor.png")); // NOI18N
        jPanel1.add(jButton3);
        jButton3.setBounds(220, 380, 64, 80);

        jLabel5.setFont(new java.awt.Font("Footlight MT Light", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Documents\\contractor.png")); // NOI18N
        jLabel5.setText("Add Contractor");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(220, 390, 330, 64);

        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setRolloverIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Documents\\NetBeansProjects\\data_base_managment\\src\\grp\\details1.png")); // NOI18N
        jButton4.setRolloverSelectedIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Documents\\NetBeansProjects\\data_base_managment\\src\\grp\\details1.png")); // NOI18N
        jPanel1.add(jButton4);
        jButton4.setBounds(220, 480, 64, 80);

        jLabel6.setFont(new java.awt.Font("Footlight MT Light", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Documents\\NetBeansProjects\\data_base_managment\\src\\grp\\details1.png")); // NOI18N
        jLabel6.setText("Contractor Details");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(220, 490, 400, 64);

        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.setRolloverIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Documents\\NetBeansProjects\\data_base_managment\\src\\grp\\finance.png")); // NOI18N
        jButton5.setRolloverSelectedIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Documents\\NetBeansProjects\\data_base_managment\\src\\grp\\finance.png")); // NOI18N
        jPanel1.add(jButton5);
        jButton5.setBounds(220, 570, 64, 80);

        jLabel7.setFont(new java.awt.Font("Footlight MT Light", 0, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grp/finance.png"))); // NOI18N
        jLabel7.setText("Finance Details");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(220, 580, 360, 64);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grp/MainPage.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1350, 720);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1342, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        this.dispose();
        addcustomer a = new addcustomer();
        a.setVisible(true);
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new main_page().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(main_page.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
